### ISSUE TITLE
Busybox doesn't build on 2.6.32-XXX

### ISSUE THREAD

**Issue by jmstover** [warewulf/warewulf3#93]
The updated busybox (1.26.2) doesn't build on RHEL 6.x systems. It's looking from 3.x kernel defines.

For example:
```
miscutils/nandwrite.c:151: error: ‘MTD_FILE_MODE_RAW’ undeclared (first use in this function)
```

In the `mtd-abi.h` in the 3.x Kernel, this is defined correct. But in the 2.6.32-XXX RHEL kernel, it is defined as `MTD_MODE_RAW`.

There's ... not really a good fix here. There's other issues that pop up if using a 6.x based OS.

Mostly this is a FYI...

-J

**Comment by bensallen** [comment]
Is there a config option to just not build nandwrite, or is this function used elsewhere as well?

Also thoughts on semi-officially dropping support for RHEL6/CentOS6 going forward?

**Comment by jmstover** [comment]
I think eventually support is going to need to be dropped.

And that's was only one of the errors. If you fix that error, then you run into other changes that cause build issues.

-J

**Comment by DLAtWork** [comment]
Hey, I submitted PR #122 to address these BusyBox issues. I'm a sysadmin, not a programmer and this is my first PR to a project so, please, criticize away.

**Comment by bensallen** [comment]
With #122 merged, closing this.
